version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: normo-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=normo_user
      - MONGO_INITDB_ROOT_PASSWORD=normo_password
      - MONGO_INITDB_DATABASE=normo_db
    volumes:
      - mongodb_data:/data/db
      - ./normo_backend/mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - normo-network
    restart: unless-stopped

  backend:
    build:
      context: ./normo_backend
      dockerfile: Dockerfile
    container_name: normo-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
      - MONGODB_URL=mongodb://normo_user:normo_password@mongodb:27017/normo_db?authSource=admin
    volumes:
      - ./normo_backend/vector_store:/app/vector_store
      - ./normo_backend/arch_pdfs:/app/arch_pdfs
      - ./normo_backend/conversations:/app/conversations
    depends_on:
      - mongodb
    networks:
      - normo-network
    restart: unless-stopped

  frontend:
    build:
      context: ./normo_frontend
      dockerfile: Dockerfile
    container_name: normo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - normo-network
    restart: unless-stopped

networks:
  normo-network:
    driver: bridge

volumes:
  vector_store:
  arch_pdfs:
  mongodb_data:
